import { Router } from 'express';

// Middleware
import { getXuser } from '../middleware/auth/index';

// Controllers
import project from '../controller/project-creation/project';
import offTimeManagement from '../controller/off-time-management';
import stateRule from '../controller/state-rule';
import task from '../controller/project-creation/task';
import taskList from '../controller/project-creation/taskList';
import subTask from '../controller/project-creation/sub-task';
import equipment from '../controller/equipments';
import meetings from '../controller/project-creation/meetings';
import projectDocuments from '../controller/project-creation/project-documents';
import projectContacts from '../controller/project-creation/contact';
import projectNotes from '../controller/project-creation/notes';
import clone from '../controller/project-creation/clone-project';
import checkList from '../controller/inspection-report/checklist-inspection';
import field from '../controller/inspection-report/field-inspection';
import weather from '../controller/weather';
import mail from '../controller/email';
import schedule from '../controller/scheduler/helper/index';
import loadlistCategory from '../controller/project-creation/load-list-category';
import loadlistTemplate from '../controller/project-creation/load-list-template';
import loadlist from '../controller/project-creation/load-list';
import medical from '../controller/project-creation/medical';
import report from '../controller/report';
import googleApis from '../controller/google-apis';
import myTask from '../controller/my-task';
import documentType from '../controller/configuration/document-type';
import myDocument from '../controller/my-document';
import activityLogs from '../controller/activity-logs';
import employeeSkills from '../controller/configuration/employee-skills';
import employeeRestrictions from '../controller/configuration/employee-restrictions';
import travelAccounts from '../controller/configuration/travel-accounts';
import userDetails from '../controller/users';
import taskListTemplate from '../controller/project-creation/taskList-template';
import fieldNotes from '../controller/field-notes';
import activities from '../controller/configuration/activities';
import repairMaintenance from '../controller/repair-maintenance';
import projectType from '../controller/configuration/project-type';
import projectStatus from '../controller/configuration/project-status';
import generalTaskList from '../controller/my-task/general-tasklist';
import generalTaskListTemplate from '../controller/my-task/general-tasklist-template';
import keywords from '../controller/configuration/keywords';
import groups from '../controller/groups';
import dailyReports from '../controller/daily-reports';
import migrationRouter from '../controller/migrations';
import equipMappingRouter from '../controller/equip-mapping';
import waterSourceRouter from '../controller/water-source';
import holeInfoRouter from '../controller/hole-info';
import utilityLocatesRouter from '../controller/project-creation/utility-locates';
import partsDetailsRouter from '../controller/equipments/parts-details';
import announcementRouter from '../controller/bulletin-notes/announcement';
import locationRouter from '../controller/bulletin-notes/location';
import projectSummaryRouter from '../controller/project-creation/project-summary';
import projectEstimateRouter from '../controller/project-creation/project-estimate';
import inspectionItemRouter from '../controller/job-site-equip-inspection/inspection-items';
import inspectionConfigRouter from '../controller/job-site-equip-inspection/inspection-config';
import inspectionFormRouter from '../controller/job-site-equip-inspection/inspection-form';
import inspectionResponseRouter from '../controller/job-site-equip-inspection/inspection-response';
import equipCategoryRouter from '../controller/equipments/equipment-category';
import dashboardRouter from '../controller/dashboard';
import userAuditLogs from '../controller/user-audit-logs';
import perDiemRouter from '../controller/project-creation/per-diem';
import projectRequirements from '../controller/project-creation/project-requirement';
import expenseReports from '../controller/project-creation/expense-report';
import pushNotifications from '../controller/push-notification';
import equipDocRouter from '../controller/equipments/documents';
import companyCodes from '../controller/company/codes';
import scheduleDailyReport from '../controller/daily-reports/schedule-daily-report';
import companyFormManual from '../controller/company/form-manuals';
import companyTrainingTest from '../controller/company/training-test';
import companyTrainingLinks from '../controller/company/training-links';
import companyLicense from '../controller/company/license';
import testQuestion from '../controller/company/training-test/questions/index';
import companyTroubleshooting from '../controller/company/troubleshooting-tips';
import companyPayroll from '../controller/company/payroll';
import companySDSList from '../controller/company/sds-list';
import companySDSDocument from '../controller/company/sds-list/sds-document';
import questionMapping from '../controller/company/training-test/question-mapping';
import customSDS from '../controller/company/sds-list/sds-custom';
import equipmentAdditionalData from '../controller/equipments/additional-detail';
import estimates from '../controller/project-creation/project-estimate/apis/index';
import perDiemSchedule from '../controller/project-creation/per-diem/per-diem-schedule';
import additionalScheduleData from '../controller/scheduler/additional-schedule';
import schedulerConflicts from '../controller/scheduler/schedulerConflicts/index';
import companyDetails from '../controller/company/details';
import holidays from '../controller/scheduler/holidays/index';
import scheduleEmployeeMapping from '../controller/scheduler-employee-mapping/index';
import generateProjectDocument from '../controller/project-creation/generate-document';
import tailgateDocument from '../controller/project-creation/tailgate-doc';
import reportEstimateMapping from '../controller/project-creation/report-estimate-mapping';
import companyReporting from '../controller/company/reporting';
import equipmentExpiryRouter from '../controller/equipments/equipment-expiry';
import allDailyReports from '../controller/daily-reports/all-daily-reports';
import projectWaterSource from '../controller/project-creation/project-water-source';
import companyIncidentReports from '../controller/company/incident-reports';
import internalRoutes from '../controller/internal-apis';
import { projectCountRouter } from '../controller';

const router = Router();
router.use('/', (req, res, next) => {

  next();
});

router.use('/holiday', holidays);
router.use('/project/medical', medical);
router.use('/project', project);
router.use('/mail', mail);
router.use('/equipment', equipment);
router.use('/equipment-expiry', getXuser, equipmentExpiryRouter);
router.use('/task', task);
router.use('/task-list', taskList);
router.use('/sub-task', subTask);
router.use('/project-documents', projectDocuments);
router.use('/contacts', projectContacts);
router.use('/notes', getXuser, projectNotes);
router.use('/meetings', meetings);
router.use('/off-time-management', offTimeManagement);
router.use('/state-rule', stateRule);
router.use('/check-list', checkList);
router.use('/field-inspection', field);
router.use('/weather', weather);
router.use('/clone', clone);
router.use('/schedule', getXuser, schedule);
router.use('/loadlist-category', getXuser, loadlistCategory);
router.use('/loadlist-template', loadlistTemplate);
router.use('/loadlist', loadlist);
router.use('/report', report);
router.use('/google-apis', googleApis);
router.use('/my-task', myTask);
router.use('/document-type', documentType);
router.use('/my-document', myDocument);
router.use('/activity-logs', activityLogs);
router.use('/employee-skills', employeeSkills);
router.use('/employee-restrictions', employeeRestrictions);
router.use('/travel-account', travelAccounts);
router.use('/user', userDetails);
router.use('/task-list-template', taskListTemplate);
router.use('/field-notes', fieldNotes);
router.use('/activities', activities);
router.use('/repair-maintenance', repairMaintenance);
router.use('/project-type', projectType);
router.use('/project-status', projectStatus);
router.use('/general-tasklist', generalTaskList);
router.use('/general-tasklist-template', generalTaskListTemplate);
router.use('/keywords', keywords);
router.use('/groups', groups);
router.use('/my-daily-report', getXuser, dailyReports);
router.use('/migration', migrationRouter);
router.use('/equip-mapping', equipMappingRouter);
router.use('/water-source', getXuser, waterSourceRouter);
router.use('/project-water-source', getXuser, projectWaterSource);
router.use('/hole-info', holeInfoRouter);
router.use('/utility-locates', utilityLocatesRouter);
router.use('/bullet-in-announcement', announcementRouter);
router.use('/bullet-in-location', locationRouter);
router.use('/project-summary', projectSummaryRouter);
router.use('/project-estimate', projectEstimateRouter);
router.use('/parts', partsDetailsRouter);
router.use('/inspection-item', inspectionItemRouter);
router.use('/inspection-config', inspectionConfigRouter);
router.use('/inspection-form', inspectionFormRouter);
router.use('/inspection-response', inspectionResponseRouter);
router.use('/equip-category', equipCategoryRouter);
router.use('/dashboard', dashboardRouter);
router.use('/user-audit-logs', userAuditLogs);
router.use('/per-diem', perDiemRouter);
router.use('/project-requirement', projectRequirements);
router.use('/expense', expenseReports);
router.use('/notifications', pushNotifications);
router.use('/equip-docs', getXuser, equipDocRouter);
router.use('/company/codes', companyCodes);
router.use('/project-schedule-report', scheduleDailyReport);
router.use('/company/forms-manuals', companyFormManual);
router.use('/company/training-test', companyTrainingTest);
router.use('/company/training-link', companyTrainingLinks);
router.use('/company/license', companyLicense);
router.use('/company/incident-reports', getXuser, companyIncidentReports);
router.use('/company/test-questions', testQuestion);
router.use('/company/question-mapping', questionMapping);
router.use('/company/troubleshooting-tips', companyTroubleshooting);
router.use('/company/payroll', companyPayroll);
router.use('/company/safety-sheet', companySDSList);
router.use('/company/safety-sheet-docs', companySDSDocument);
router.use('/company/custom-safety-sheet', customSDS);
router.use('/equipment-additional', equipmentAdditionalData);
router.use('/estimates', getXuser, estimates);
router.use('/per-diem-schedule', perDiemSchedule);
router.use('/equipment-inspection-form', inspectionFormRouter);
router.use('/equipment-inspection-item', inspectionItemRouter);
router.use('/equipment-inspection-config', inspectionConfigRouter);
router.use('/equipment-inspection-response', inspectionResponseRouter);
router.use('/additional-schedule', additionalScheduleData);
router.use('/scheduler-conflicts', schedulerConflicts);
router.use('/company/details', companyDetails);
router.use('/schedule-employee-mapping', getXuser, scheduleEmployeeMapping);
router.use('/generate-project-doc', getXuser, generateProjectDocument);
router.use('/tailgate-doc', getXuser, tailgateDocument);
router.use('/project-invoicing', getXuser, reportEstimateMapping);
router.use('/company/reporting', getXuser, companyReporting);
router.use('/all-daily-reports', getXuser, allDailyReports);
router.use('/project-count', getXuser, projectCountRouter);
router.use('/internal-api', internalRoutes);

export default router;